apiVersion: v1
kind: Service
metadata:  
  name: nginx
spec:
  selector:    
    app: my-app
  type: LoadBalancer
  ports:  
  - name: http
    port: 8080
    targetPort: 8080       
    protocol: TCP